services:
  - type: web
    name: spot-the-errors-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build --workspace=server
    startCommand: npm run start --workspace=server
    envVars:
      - key: PORT
        value: 5000
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
